package reto3;

import javax.swing.JOptionPane;
import Controller.*;
import javax.swing.table.DefaultTableModel;
import Classes.*;
import java.awt.Color;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.Date;
import javax.swing.JTable;

public class reto3JFrame extends javax.swing.JFrame {
//--->        //  CONTROLLERS  //
        ctlShopCart ctlCart = new ctlShopCart();        
        ctlItemLine ctlLine = new ctlItemLine();
        ctlClient ctlClient = new ctlClient();
        ctlItem ctlItem = new ctlItem();
        ctlOrder ctlOrder = new ctlOrder();
        ctlPayment ctlPay = new ctlPayment();
        ctlSend ctlSend = new ctlSend();
        ctlHistorical ctlHistory = new ctlHistorical();
        Login Login;
//--->        //  BOARDS  //
        DefaultTableModel tableStock;
        DefaultTableModel cartStock;
        DefaultTableModel historyStock;
//--->        //  ENTITIES  //
        ShopCart shopCart;
        NaturalClient natClient;
        LegalClient legClient;
        Client Client;
        Order order;
        Payment pay;
        Send send;
        Date orderDate;
        Date payDate;
//--->        //  UTILITY DATAS  //
        String itemID;
        String cartItemID;
        double itemPrice;
        int clientID;
        String clientType;
        String sendAddress;
        //int orderID;       
        //int paymentID;
        //int sendID;       
        //String sendCompany;
    
    public reto3JFrame(NaturalClient client) {
        initComponents();
        setLocationRelativeTo(null);
        natClient = client;
        clientID = natClient.getId();
        clientType = natClient.clientType();
        stocker();
        loadData(natClient.clientType());
        confProfileFields();
        refreshShopCart(cartTable);
        updateHistoryTable(historyTable);
    }

    public reto3JFrame(LegalClient client) {
        initComponents();
        setLocationRelativeTo(null);
        legClient = client;
        clientID = legClient.getId();
        clientType = legClient.clientType();
        stocker();
        loadData(legClient.clientType());
        confProfileFields();
        refreshShopCart(cartTable);
        updateHistoryTable(historyTable);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemLineFrame = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        cbAmountLine = new javax.swing.JComboBox<>();
        btnItemLineOk = new javax.swing.JButton();
        Group1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        storeTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_itemsCart = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cartID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_cartTimeLess = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_cartCost = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btn_ItemLineDel = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JToggleButton();
        btn_cancelOrder = new javax.swing.JButton();
        txt_status = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_pay = new javax.swing.JButton();
        btn_receive = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cb_sendCompany = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        btnFinish = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txt_identify = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_NIT = new javax.swing.JTextField();
        txt_company = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_names = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_lastnames = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txt_mail = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txt_newPassword = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        txt_newPass = new javax.swing.JPasswordField();
        txt_oldPassword = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnNewCart = new javax.swing.JToggleButton();
        delShopCart = new javax.swing.JButton();
        btnLogout = new javax.swing.JLabel();

        itemLineFrame.setTitle("Item Line");
        itemLineFrame.setLocation(new java.awt.Point(500, 250));
        itemLineFrame.setUndecorated(true);
        itemLineFrame.setResizable(false);
        itemLineFrame.setSize(new java.awt.Dimension(250, 150));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 5, true));

        jLabel21.setText("How many items to add to cart?");

        cbAmountLine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAmountLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAmountLineActionPerformed(evt);
            }
        });

        btnItemLineOk.setText("OK");
        btnItemLineOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemLineOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel21)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnItemLineOk, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAmountLine, 0, 0, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAmountLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnItemLineOk)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout itemLineFrameLayout = new javax.swing.GroupLayout(itemLineFrame.getContentPane());
        itemLineFrame.getContentPane().setLayout(itemLineFrameLayout);
        itemLineFrameLayout.setHorizontalGroup(
            itemLineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLineFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemLineFrameLayout.setVerticalGroup(
            itemLineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLineFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping System");
        setLocation(new java.awt.Point(0, 0));
        setName("FR_system"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));

        storeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category", "Supplier", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        storeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(storeTable);
        if (storeTable.getColumnModel().getColumnCount() > 0) {
            storeTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/arrow, sign, down, downwards, download_24px.png"))); // NOI18N
        jLabel15.setText("Select items from the list to add them to the cart");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Store Inventary", jPanel1);

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Amount", "Category", "Supplier", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cartTable);
        if (cartTable.getColumnModel().getColumnCount() > 0) {
            cartTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            cartTable.getColumnModel().getColumn(1).setPreferredWidth(5);
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/windshield, wipers, car, vehicle, transportation_24px.png"))); // NOI18N
        jLabel2.setText("Items in Cart:");

        txt_itemsCart.setEditable(false);
        txt_itemsCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemsCartActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/ecology, plant, tag, organic_24px.png"))); // NOI18N
        jLabel3.setText("Cart ID");

        txt_cartID.setEditable(false);
        txt_cartID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cartIDActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/timer, stopwatch, setting, options, preferences_24px.png"))); // NOI18N
        jLabel13.setText("Cart Time Less");

        txt_cartTimeLess.setEditable(false);
        txt_cartTimeLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cartTimeLessActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/coin, money, finance, payment_24px.png"))); // NOI18N
        jLabel14.setText("Cart Cost:");

        txt_cartCost.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setText("This is the order that you are going to carry out:");

        btn_ItemLineDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/trash, garbage, can, bin, ecology_24px.png"))); // NOI18N
        btn_ItemLineDel.setText("Delete Item Line");
        btn_ItemLineDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ItemLineDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btn_ItemLineDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cartTimeLess, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cartID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_itemsCart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cartCost, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_cartID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(txt_cartTimeLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_ItemLineDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_cartCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_itemsCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("My Shopping Cart", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Client Data"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Manage"));

        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/buy, click, button, hand, gesture_24px.png"))); // NOI18N
        btnOrder.setText("Realize Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btn_cancelOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/alert, danger, warning, notification_24px.png"))); // NOI18N
        btn_cancelOrder.setText("Cancel Order");
        btn_cancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelOrderActionPerformed(evt);
            }
        });

        txt_status.setEditable(false);
        txt_status.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_statusActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/timer, hourglass, time, clock_24px.png"))); // NOI18N
        jLabel4.setText("Order Status :");

        btn_pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/bitcoin, currency, finance, chart, graph_24px.png"))); // NOI18N
        btn_pay.setText("Pay Order");
        btn_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payActionPerformed(evt);
            }
        });

        btn_receive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/rocket, startup, monitor, screen, computer_24px.png"))); // NOI18N
        btn_receive.setText("Send Order");
        btn_receive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receiveActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("1°");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("2°");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("3°");

        cb_sendCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FEDEX", "SERVIENTREGA", "INTERR" }));

        jLabel20.setText("Sends Company");

        btnFinish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/download, down, arrow, browser, webpage_24px.png"))); // NOI18N
        btnFinish.setText("FINISH ORDER");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_pay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_receive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_sendCompany, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cancelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOrder)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_pay)
                                    .addComponent(jLabel18)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cancelOrder)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(btn_receive))
                            .addComponent(btnFinish)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_sendCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "STATUS", "ORDER DATE", "PAYMENT DATE", "SEND DATE", "SEND COMPANY", "ITEMS AMOUNTS", "PAYMENT"
            }
        ));
        jScrollPane3.setViewportView(historyTable);
        if (historyTable.getColumnModel().getColumnCount() > 0) {
            historyTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            historyTable.getColumnModel().getColumn(5).setPreferredWidth(50);
            historyTable.getColumnModel().getColumn(6).setPreferredWidth(30);
            historyTable.getColumnModel().getColumn(7).setPreferredWidth(70);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sales Manager", jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Profile Information"));

        txt_identify.setEditable(false);

        jLabel5.setText("Identification:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("NIT:");

        txt_NIT.setEditable(false);
        txt_NIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NITActionPerformed(evt);
            }
        });

        txt_company.setEditable(false);
        txt_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_companyActionPerformed(evt);
            }
        });

        jLabel12.setText("Company:");

        txt_names.setEditable(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Names:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Lastnames:");

        txt_lastnames.setEditable(false);
        txt_lastnames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastnamesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_names)
                    .addComponent(txt_identify, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_lastnames, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NIT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txt_names, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_lastnames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_identify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txt_NIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Information"));

        txt_mail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_address.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Address:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Phone:");

        txt_phone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setText("Mail:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/brain, storming, settings, thought, preferences_24px.png"))); // NOI18N
        jButton1.setText("Update ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Segurity Information"));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("New Password: ");

        jLabel25.setText("Confirm Password: ");

        txt_oldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_oldPasswordActionPerformed(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Old Password :");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/settings, options, preferences, gears_24px.png"))); // NOI18N
        jButton2.setText("Change Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_oldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(txt_newPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_newPass))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txt_newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txt_oldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Profile", jPanel6);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 48)); // NOI18N
        jLabel1.setText("Shopping System");

        btnNewCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/open, trunk, car, vehicle, transportation_24px.png"))); // NOI18N
        btnNewCart.setText("New Shopping Cart");
        btnNewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCartActionPerformed(evt);
            }
        });

        delShopCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/garbage, truck, transportation, transport, vehicle_24px.png"))); // NOI18N
        delShopCart.setText("Decline Shopping Cart");
        delShopCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delShopCartActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("ROG Fonts", 2, 14)); // NOI18N
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppData/teamwork, team, woman, account, profile_24px.png"))); // NOI18N
        btnLogout.setText(">>log Out");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(delShopCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNewCart, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewCart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delShopCart)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCartActionPerformed
            if(!Objects.isNull(shopCart)){
               JOptionPane.showMessageDialog(this, "You already have an active shopping cart. You can decline the current shopping cart to get another one.");
               refreshShopCart(cartTable);
            }else{
            shopCart = new ShopCart(LocalDateTime.MAX, clientID);
            ctlCart.newShopCart(shopCart);
            refreshShopCart(cartTable);
            JOptionPane.showMessageDialog(null, "You have a new shopping cart");
        }   
    }//GEN-LAST:event_btnNewCartActionPerformed

    private void delShopCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delShopCartActionPerformed
        if(Objects.isNull(shopCart)){
               JOptionPane.showMessageDialog(this, "You do not have shopping carts to decline");
               //updateCart();
               //refreshShopCart(cartTable);
            }else{    
                delShopCart();
        }
    }//GEN-LAST:event_delShopCartActionPerformed

    private void txt_lastnamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastnamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastnamesActionPerformed

    private void txt_cartIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cartIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cartIDActionPerformed

    private void txt_cartTimeLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cartTimeLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cartTimeLessActionPerformed

    private void txt_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_companyActionPerformed

    private void btn_ItemLineDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ItemLineDelActionPerformed
        // TODO add your handling code here:
        ctlLine.delItemLine(cartItemID);
        //loadShopCart();
        //updateCart();
        refreshShopCart(cartTable);
    }//GEN-LAST:event_btn_ItemLineDelActionPerformed

    private void storeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeTableMouseClicked
        // TODO add your handling code here:
        // ----------> MAUSE CLICKED
        if(shopCart == null){
           JOptionPane.showMessageDialog(this, "You don't have a shopping cart "); 
        }else{
        int fila= storeTable.getSelectedRow(); //es la fila que se va a cargar
        itemID= storeTable.getValueAt(fila,0).toString();            
//setItemID(Integer.parseInt((String)storeTable.getValueAt(fila,0).toString()));
        System.out.println(itemID);
        itemPrice = (double)storeTable.getValueAt(fila, 3);
        //System.out.println(itemPrice);
        itemLineFrame.setVisible(true);
        }
    }//GEN-LAST:event_storeTableMouseClicked

    private void btnItemLineOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemLineOkActionPerformed
        // TODO add your handling code here:
        //String sAmount = (String)cbAmountLine.getSelectedItem();
        int amount = Integer.parseInt(cbAmountLine.getSelectedItem().toString());
        if(amount >0){
            System.out.println(amount);
            double subtotal = itemPrice * amount;
            System.out.println(subtotal);
            ItemLine nwLine = new ItemLine(amount, subtotal, itemID, (Integer)shopCart.getId());
            itemLineFrame.dispose();
            ctlLine.addItemLine(nwLine);
            JOptionPane.showMessageDialog(this, "Items added to cart");
            cbAmountLine.setSelectedIndex(0);
        //loadShopCart();
        //updateCart();
        refreshShopCart(cartTable);       
        }else{
            itemLineFrame.dispose();
        }
    }//GEN-LAST:event_btnItemLineOkActionPerformed

    private void txt_itemsCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemsCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemsCartActionPerformed

    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked

       int fila= cartTable.getSelectedRow(); //es la fila que se va a cargar
        cartItemID = cartTable.getValueAt(fila,0).toString();        
    }//GEN-LAST:event_cartTableMouseClicked

    private void txt_NITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NITActionPerformed

    private void cbAmountLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAmountLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAmountLineActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        if(!Objects.isNull(send)){
            order.setStatus("FINISHED");
            recHistorical(order.getStatus());
            updateHistoryTable(historyTable);
            resetOrder();
            txt_itemsCart.setText("");
            txt_cartCost.setText("");
            delShopCart();
            shopCart= null;
            JOptionPane.showMessageDialog(this, "We have finished. Thank you for using our services.");
        }else{
            JOptionPane.showMessageDialog(this, "You can only finish this operation when the status of the order is: sent");
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btn_receiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receiveActionPerformed
        if(!Objects.isNull(send)){
            JOptionPane.showMessageDialog(this, "This order has already been shipped. check your email");
        }else if(!Objects.isNull(pay)){
            Date send_date = new Date();
            String send_company= cb_sendCompany.getSelectedItem().toString();
            int payment_id= pay.getId();
            int order_id = order.getId();
            //String send_address = sendAddress;
            send = new Send(0, sendAddress, send_date, send_company, payment_id, order_id);
            //System.out.println(send.getSendDate());
            int sendID= ctlSend.addSend(send);
            if(sendID >0){
                send.setId(sendID);
                ctlSend.updateOrderStatus(clientID);
                order.setStatus("SENT");
                txt_status.setText(order.getStatus());
                JOptionPane.showMessageDialog(this, "The order has been sent to your address. Shipping information will also be sent to your email.");
            }
        }else{
            JOptionPane.showMessageDialog(this, "First make the payment of the order");
        }
    }//GEN-LAST:event_btn_receiveActionPerformed

    private void btn_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payActionPerformed
        if(!Objects.isNull(pay)){
            JOptionPane.showMessageDialog(this, "Payment has already been received for this order.");
        }else if(!Objects.isNull(order)){
            payDate = new Date();
            double payment= Double.parseDouble(shopCart.getTotalPrice());
            int order_id= order.getId();
            pay = new Payment(0, payDate, payment, order_id);
            int paymentID= ctlPay.addPayment(pay);
            if(paymentID >0){
                pay.setId(paymentID);
                ctlPay.updateOrderStatus(order.getId());
                order.setStatus("PAYDED");
                txt_status.setText(order.getStatus());
                JOptionPane.showMessageDialog(this, "Your payment has been received. now you can request a shipment.");
            }
        }else{
            //JOptionPane.showMessageDialog(this, "The payment for this order has already been processed");
            JOptionPane.showMessageDialog(this, "make an order first");
        }
    }//GEN-LAST:event_btn_payActionPerformed

    private void txt_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusActionPerformed

    private void btn_cancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelOrderActionPerformed
        if(!Objects.isNull(send)){
            JOptionPane.showMessageDialog(this, "Your order has already been sent, FINISH the operation.");
        }else if(!Objects.isNull(pay)){
            JOptionPane.showMessageDialog(this, "No money back, sorry.");
        }else if(!Objects.isNull(order)){
            order.setStatus("CANCELED");
            recHistorical(order.getStatus());
            updateHistoryTable(historyTable);
            resetOrder();
            JOptionPane.showMessageDialog(this, "Order was canceled");
        }else{
            JOptionPane.showMessageDialog(this, "You don't have an order that you can cancel");
        }
    }//GEN-LAST:event_btn_cancelOrderActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
//        if(!rb_person.isSelected() && !rb_company.isSelected()){
//            JOptionPane.showMessageDialog(this, "Select a Person or Company");
//        }
        if(cartTable.getRowCount() < 1){
            JOptionPane.showMessageDialog(this, "Add products on you Shop Cart");
        }else if(!Objects.isNull(order)){
            //System.out.println("will create client");
            JOptionPane.showMessageDialog(this, "You already have an order in process. Only one order can be processed at a time.");
        }else{
                newOrder();
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void txt_oldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_oldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_oldPasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String oldPassword= txt_oldPassword.getText();
        String newPassword= txt_newPassword.getText();
        String newPass= txt_newPass.getText();
        if(!newPassword.equals(newPass)){
            JOptionPane.showMessageDialog(this, "Passwords don't match");
        }else{
            if(ctlClient.verifyKey(clientID, oldPassword)){
                if(ctlClient.updateUserKey(clientID, newPassword)){
                    JOptionPane.showMessageDialog(this, "password was updeted");
                }
            }else{
                JOptionPane.showMessageDialog(this, "old password is wrong");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String address = txt_address.getText();
        String mail = txt_mail.getText();
        String phone = txt_phone.getText();
        try{
        switch(clientType){
            case "legal":
                legClient.setAddress(address);
                legClient.setMail(mail);
                legClient.setPhone(phone);
                //LegalClient client = new LegalClient(legClient.getCompany(), legClient.getNIT(), legClient.getId(), address, phone, mail);
                if(ctlClient.updateClient(legClient)){
                    JOptionPane.showMessageDialog(this, "Information was Updated");
                }
            case "natural":
                natClient.setAddress(address);
                natClient.setMail(mail);
                natClient.setPhone(phone);
                if(ctlClient.updateClient(natClient)){
                    JOptionPane.showMessageDialog(this, "Information was Updated");
                }
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setForeground(Color.red);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setForeground(Color.black);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
//--->  // RESET ENTITIES  //        
        ShopCart shopCart = null;
        NaturalClient natClient = null;
        LegalClient legClient = null;
        Client Client = null;
        Order order = null;
        Payment pay = null;
        Send send = null;
        Date orderDate = null;
        Date payDate = null;
//--->  // RESET UTILITY DATAS  //
        String itemID = null;
        String cartItemID = null;
        double itemPrice = 0;
        int clientID = 0;
        String clientType = null;
        String sendAddress = null;
//--->      // RESET TEXT FIELDS  //        
                    txt_identify.setText("");
                    txt_names.setText("");
                    txt_lastnames.setText("");
                    txt_NIT.setText("");
                    txt_company.setText("");
                    txt_address.setText("");
                    txt_phone.setText("");
                    txt_mail.setText("");
                    txt_status.setText(""); 
        this.dispose();
        Login = new Login();
        Login.setVisible(true);
        
    }//GEN-LAST:event_btnLogoutMouseClicked

    public void cleanCartTable(){
        if (cartStock != null){
        for(int i=0;i<cartTable.getRowCount();i++){
            cartStock.removeRow(i);
            i=i-1;
            }
        }
    }    
    
    public void updateHistoryTable(JTable model){
        if (historyStock != null){
        for(int i=0;i<historyTable.getRowCount();i++){
            historyStock.removeRow(i);
            i=i-1;
            }
        }
            //cleanHistoryTable();
            historyStock = ctlHistory.updateHistorical(model, clientID);
            historyTable.setModel(historyStock);
    } 
    
    private void stocker(){
        storeTable.setModel(ctlItem.loadStock(storeTable));
    }
    
    private ShopCart refreshShopCart(JTable model){
        try{
            shopCart = ctlCart.loadShopCart(clientID);
                
            txt_cartTimeLess.setText(shopCart.timeLess());                                        
            txt_cartID.setText(Integer.toString(shopCart.getId()));
            txt_cartTimeLess.setText(shopCart.timeLess());
            txt_itemsCart.setText(shopCart.getAmounts());
            txt_cartCost.setText(shopCart.getTotalPrice());
                
            cleanCartTable();
            cartStock = ctlCart.updateShopCart(model, shopCart.getId());        
            cartTable.setModel(cartStock);
                
            if(shopCart.checkTimeLimi()){
                delShopCart();
            }
            return shopCart;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "You must have an active shopping cart to select your products, this cart will expire in 24 hours ");
        } 
        return null;
    }
       
    private void delShopCart(){      
        if(this.ctlCart.delShopCart(shopCart.getId()) == true){
            txt_cartTimeLess.setText("");
            txt_cartID.setText("");
            txt_itemsCart.setText("");
            txt_cartCost.setText("");
            cleanCartTable();
            shopCart = null;                    
            JOptionPane.showMessageDialog(this, "the shopping cart was declined"); 
            }                
        }    
    
    private boolean newOrder(){
        if(Objects.isNull(order)){
            orderDate = new Date();
            String status = "WAITING";
            double cost = Double.parseDouble(shopCart.getTotalPrice());
            int client_ID =clientID;
            int cart_ID = shopCart.getId();
            order = new Order(0, orderDate, status, cost, client_ID);
            int orderID= ctlOrder.newOrder(order);            
                if(orderID > 0){
                    order.setId(orderID);
                    txt_status.setText(order.getStatus());
                    JOptionPane.showMessageDialog(this, "New order in process. Pay the order to request a shipment.");
                    return true;  
                }                               
        }else{
            JOptionPane.showMessageDialog(this, "You already have an order in process. Only one order can be processed at a time.");            
        }return false;
    }
        
    private void loadData(String clientType){
        setClientData(clientType);
        shopCart = ctlCart.loadShopCart(clientID);
        order= ctlOrder.loadOrder(clientID);
        if(!Objects.isNull(order)){
            txt_status.setText(order.getStatus());
            pay= ctlPay.loadPayment(order.getId());
            if(!Objects.isNull(pay)){
                send= ctlSend.loadSend(pay.getId());                                     
            }
        }
    }
    
    private boolean setClientData(String clientType){ 
        System.out.println(clientType);
        try{               
            switch(clientType){
                case "legal":
                        txt_NIT.setText(legClient.getNIT());
                        txt_company.setText(legClient.getCompany());
                        txt_address.setText(legClient.getAddress());
                        txt_phone.setText(legClient.getPhone());
                        txt_mail.setText(legClient.getMail());
                        sendAddress= legClient.getAddress();
                        return true;
                case "natural":
                        txt_identify.setText(natClient.getIdentification());
                        txt_names.setText(natClient.getNames());
                        txt_lastnames.setText(natClient.getLastnames());
                        txt_address.setText(natClient.getAddress());
                        txt_phone.setText(natClient.getPhone());
                        txt_mail.setText(natClient.getMail());
                        sendAddress= natClient.getAddress();
                        return true;
            }                               
        }catch(Exception e){                        
        }return false;
    }
        
    private void resetOrder(){ // NO INCLUYE AL SHOPCART              
        ctlOrder.delOrder(order.getId());
        order = null;
        pay= null;
        send= null;
        //ctlPay.delPayment(pay.getId());
        //ctlSend.delSend(send.getId());
        //ctlCart.delShopCart();
        //shopCart = null;        
        //natClient = null;
        //legClient = null;        
        txt_status.setText("");    
    }

    private boolean recHistorical(String orderStatus){
        switch(orderStatus){
            case "FINISHED" -> {       
                int items = Integer.parseInt(shopCart.getAmounts());
                double cost = Double.parseDouble(shopCart.getTotalPrice());
                Historical his = new Historical(order.getId(), order.getOrderDate(), "FINISHED", cost, items, pay.getPayDate(), send.getSendDate(), send.getSendCompany(), clientID);
                if(ctlHistory.addHistory(his)){
                    return true;
                }else{
                    return false;
                }   }
            case "CANCELED" -> {
                int items = Integer.parseInt(shopCart.getAmounts());
                double cost = Double.parseDouble(shopCart.getTotalPrice());
                Historical his = new Historical(order.getId(), order.getOrderDate(), "CANCELED", cost, items, null, null, "NOT COMPANY", clientID);
                if(ctlHistory.addHistory(his)){
                    return true;
                }else{
                    return false;
                }       }
        }
        return false;
    }
    
    private void confProfileFields(){
        if(Objects.nonNull(natClient)){
            txt_NIT.setVisible(false);
            txt_company.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            
        }else if(Objects.nonNull(legClient)){
            txt_identify.setVisible(false);
            txt_names.setVisible(false);
            txt_lastnames.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(reto3JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(reto3JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(reto3JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(reto3JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new reto3JFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Group1;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnItemLineOk;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JToggleButton btnNewCart;
    private javax.swing.JToggleButton btnOrder;
    private javax.swing.JToggleButton btn_ItemLineDel;
    private javax.swing.JButton btn_cancelOrder;
    private javax.swing.JButton btn_pay;
    private javax.swing.JButton btn_receive;
    private javax.swing.JTable cartTable;
    private javax.swing.JComboBox<String> cbAmountLine;
    private javax.swing.JComboBox<String> cb_sendCompany;
    private javax.swing.JButton delShopCart;
    private javax.swing.JTable historyTable;
    private javax.swing.JFrame itemLineFrame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable storeTable;
    private javax.swing.JTextField txt_NIT;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_cartCost;
    private javax.swing.JTextField txt_cartID;
    private javax.swing.JTextField txt_cartTimeLess;
    private javax.swing.JTextField txt_company;
    private javax.swing.JTextField txt_identify;
    private javax.swing.JTextField txt_itemsCart;
    private javax.swing.JTextField txt_lastnames;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_names;
    private javax.swing.JPasswordField txt_newPass;
    private javax.swing.JPasswordField txt_newPassword;
    private javax.swing.JPasswordField txt_oldPassword;
    private javax.swing.JTextField txt_phone;
    public javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables


}
